version: '3'
services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Mount SSL certificates (if you're using Let's Encrypt)
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
