name: Build and Run Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the code from the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Set up Docker Buildx

    - name: Build Docker image
      uses: docker/build-push-action@v4  # Build the Docker image
      with:
        context: .
        push: false  # We don't push the image since we're not using DockerHub
        tags: my-python-app:latest

    - name: Run Docker container
      run: |
        docker run --env-file .env my-python-app
